- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /root/shubhangi/kubernetes_project/Deployment.yml
     - name: delete old service
       command: kubectl delete -f /root/shubhangi/kubernetes_project/Service.yml
     - name: create new deployment
       command: kubectl apply -f /root/shubhangi/kubernetes_project/Deployment.yml
     - name: create new service
       command: kubectl apply -f /root/shubhangi/kubernetes_project/Service.yml
